version: 2
jobs:
  build:
    branches:
      ignore:
        - master
        - develop
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SBT_OPTS: -Xss2m -Xms1g -Xmx3g -XX:MaxMetaspaceSize=512m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
      - run: sbt test

      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          command: |
            sbt ';++2.10.6;^^0.13.16;scripted'
            sbt ';++2.12.4;^^1.0.4;scripted'